# Generated by Django 2.0.7 on 2018-09-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('college', models.CharField(max_length=50, verbose_name='学院')),
                ('place', models.CharField(max_length=100, verbose_name='故障地点')),
                ('goods', models.CharField(max_length=100, verbose_name='故障物品')),
                ('file1', models.ImageField(upload_to='upload/fix/')),
                ('file2', models.ImageField(upload_to='upload/fix/')),
                ('detail', models.CharField(max_length=500, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '保修信息',
                'verbose_name_plural': '保修信息',
            },
        ),
    ]
