# Generated by Django 2.0.7 on 2018-09-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('types', models.CharField(max_length=100, verbose_name='活动类型')),
                ('creator_id', models.CharField(max_length=100, verbose_name='创建人id')),
                ('person', models.IntegerField(verbose_name='活动人数')),
                ('sold_ticket', models.IntegerField(verbose_name='已售票数')),
                ('times', models.DateField(verbose_name='活动时间')),
                ('place', models.CharField(max_length=100, verbose_name='活动地点')),
                ('detail', models.CharField(max_length=500, verbose_name='描述')),
                ('sign_count', models.IntegerField(default=0, verbose_name='已签到人数')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('college', models.CharField(max_length=50, verbose_name='学院')),
                ('place', models.CharField(max_length=100, verbose_name='故障地点')),
                ('goods', models.CharField(max_length=100, verbose_name='故障物品')),
                ('file1', models.ImageField(upload_to='fix', verbose_name='照片')),
                ('detail', models.CharField(max_length=500, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '报修信息',
                'verbose_name_plural': '报修信息',
                'db_table': 'fix',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(verbose_name='活动id')),
                ('person_id', models.IntegerField(verbose_name='领取人id')),
                ('is_sign', models.IntegerField(default=0, verbose_name='是否签到')),
                ('image', models.ImageField(upload_to='qr', verbose_name='二维码信息')),
            ],
            options={
                'verbose_name': '票务信息',
                'verbose_name_plural': '票务信息',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.CharField(max_length=255, verbose_name='用户id')),
                ('password', models.CharField(max_length=255)),
                ('realname', models.CharField(max_length=255)),
                ('nikename', models.CharField(max_length=255)),
                ('face', models.TextField()),
                ('classid', models.CharField(max_length=255)),
                ('is_teacher', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
    ]
