# Generated by Django 2.0.7 on 2018-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.CharField(max_length=200, verbose_name='二维码信息'),
        ),
    ]
