# Generated by Django 2.0.7 on 2018-09-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0002_remove_fix_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='file1',
            field=models.ImageField(upload_to='upload/fix'),
        ),
    ]
