# Generated by Django 2.0.7 on 2018-09-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0003_auto_20180911_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='file1',
            field=models.ImageField(upload_to='fix', verbose_name='照片'),
        ),
    ]
